# Generated by Django 5.1.3 on 2024-12-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app13', '0002_comment_edited_at_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
